#!/sbin/openrc-run
# Copyright 1999-2019 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

: ${COBBLERD_USER:=cobbler}
: ${COBBLERD_GROUP:=cobbler}
: ${COBBLERD_EXTRA_ARGS:=}
: ${COBBLERD_PIDFILE:=/run/cobblerd.pid}

command="/usr/bin/cobblerd"
command_args="-F ${COBBLERD_EXTRA_ARGS}"
command_user="${COBBLERD_USER}:${COBBLERD_GROUP}"
command_background="true"
pidfile="${COBBLERD_PIDFILE}"

depend() {
    use net logger
}
