#!/bin/sh
RIAK_COOKIE="$(grep setcookie /etc/riak/vm.args | awk '{ print $2; }')"

command="${1}"
shift
args="${*}"

output="$(riak escript ${command} --cookie ${RIAK_COOKIE} ${args})"
retcode=$?

echo $output | sed "s|${RIAK_COOKIE}|MASKED|g"
exit $retcode
