#!/bin/sh
RIAK_COOKIE="$(sudo grep setcookie /etc/riak/vm.args | awk '{ print $2; }')"

command="${1}"
shift
args="${*}"

output="$(${command} --cookie ${RIAK_COOKIE} ${args})"
retcode=$?

echo $output | sed "s|${RIAK_COOKIE}|MASKED|g"
exit $retcode
